// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpV1ymCeOCZxxIU527ruFTGBig5U-TOUw',
    appId: '1:167316056090:android:a6dcd8f07fc01a715f49a3',
    messagingSenderId: '167316056090',
    projectId: 'muzzone-3e13b',
    storageBucket: 'muzzone-3e13b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBHzy46rka2OeU2oKAqaJmBMA2vVX-pw',
    appId: '1:167316056090:ios:d4fc5de793fa01785f49a3',
    messagingSenderId: '167316056090',
    projectId: 'muzzone-3e13b',
    storageBucket: 'muzzone-3e13b.appspot.com',
    androidClientId: '167316056090-7dlss1jta9447iedgmddhvqaal9s1ent.apps.googleusercontent.com',
    iosClientId: '167316056090-f56ht3ot8su0dmfnn592fmm4c561aphb.apps.googleusercontent.com',
    iosBundleId: 'com.uz.telecom.muzzone',
  );
}
